language: cpp
os: linux
dist: focal # Ubuntu 20.04

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -- -j2

before_install:
  - sudo apt-get -y install clang-10
  - eval "CC=clang-10 && CXX=clang++-10"
