# Ubuntu 20.04
dist: focal
language: cpp

script:
  - cmake .
  - cmake --build . -- -j2

jobs:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb https://apt.llvm.org/focal/ llvm-toolchain-focal-10 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - cmake
            - clang-10
#            - clang-format-10
#            - clang-tidy-10
#            - python3
#            - python3-pip
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"

before_install:
  - eval "${MATRIX_EVAL}"
