language: cpp
os: linux
dist: focal # Ubuntu 20.04

before_install:
  - sudo apt-get -y install clang-10 clang-format-10 clang-tidy-10 python3 python3-pip
  - pip3 install cmake_format[YAML]
  - eval "CC=clang-10 && CXX=clang++-10"

jobs:
  include:
    - stage: build
      script: .travis-scripts/build.sh
    - stage: code style
      script: .travis-scripts/clang-format.sh
    - stage: tests
      script: .travis-scripts/tests.sh
    - stage: benchmarks
      script: .travis-scripts/benchmarks.sh
