language: cpp
os: linux
dist: focal # Ubuntu 20.04

before_script:
  - mkdir cmake-build
  - cd cmake-build
  - cmake ..

script:
  - cmake --build .. -- -j2

#jobs:
#  include:
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - sourceline: "deb https://apt.llvm.org/focal/ llvm-toolchain-focal-10 main"
#              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
#          packages:
#            - clang-10
#            - clang-format-10
#            - clang-tidy-10
#            - python3
#            - python3-pip
#      env:
#        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"

before_install:
  - sudo apt-get -y install clang-10
  - eval "CC=clang-10 && CXX=clang++-10"
