name: skipper-main

on: [push]

jobs:
  code-style:
    name: Code style checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          ls
          ls ..
          cd skipper
          .ci-scripts/clang-format.sh

#  build:
#    name: Build CMake project
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          submodules: true
#      - run: .ci-scripts/build.sh

#  tests:
#    name: Run tests
#    runs-on: ubuntu-20.04
#    needs: build
#    if: ${{ needs.build.result == success }}
#
#  benchmarks:
#    name: Run benchmarks
#    runs-on: ubuntu-20.04
#    needs: build
#    if: ${{ needs.build.result == success }}
