name: skipper-main

on: push

defaults:
  run:
    working-directory: .

jobs:
#  code-style:
#    name: Code style checks
#    runs-on: ubuntu-20.04

  build:
    name: Build CMake project
    runs-on: ubuntu-20.04
    outputs:
      build: ${{ steps.build.outputs }}
    steps:
      - id: build
        run: .ci-scripts/build.sh

#  tests:
#    name: Tests
#    runs-on: ubuntu-20.04
#    needs: build
#    if: ${{ needs.build.result == success }}
#
#  benchmarks:
#    name: Benchmarks
#    runs-on: ubuntu-20.04
#    needs: build
#    if: ${{ needs.build.result == success }}
