name: skipper

on: [push]

jobs:
  code-style:
    name: Code style checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get -y install clang-format-10
      - run: .ci-scripts/clang-format.sh

  build:
    name: Build CMake project
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: .ci-scripts/build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  tests:
    name: Run tests
    runs-on: ubuntu-20.04
    needs: build
    if: ${{ needs.build.result == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - run: .ci-scripts/tests.sh

  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-20.04
    needs: build
    if: ${{ needs.build.result == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - run: .ci-scripts/benchmarks.sh
